name: Lint

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  run-lint:
    name: Run lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: yarn install

      - name: Run lint
        run: yarn run lint
